# CI de Nível 04 - Pipeline Integrada ao Build do Código
name: 'N4 - Execução Integrada'

# Regras de disparo (Gatilho Manual e Push na Master)
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  NODE_VERSION: '24.x' # Mantém fixo na versão de execução estável para evitar deprecation warnings
#tarefas dentro da pipeline = jobs
jobs:
  # Job 1: Inspeção de Qualidade (Linter)
  inspecao:
  # maquina onde o job vai rodar
    runs-on: ubuntu-latest
    # passos do job
    steps:
       # Clone do projeto
        uses: actions/checkout@v4

       # instalção do node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

       # instalação do Yarn
        run: npm install -g yarn

        # instalação das dependências
      - name: Instalando dependências com Yarn
        run: yarn install

      - name: Inspeção de Código 
        run: yarn run lint
        continue-on-error: true # Se houver avisos cosméticos de formatação, a esteira avança para os testes

  # Job 2: Testes Unitários (Onde estão os seus 5 testes de sucesso)
  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao]
    
    steps:
      uses: actions/checkout@v4

      uses: actions/setup-node@v4
        with:
          node-version: latest

       - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Rodando testes unitários
        run: yarn run test

       e2e-tests:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Browsers do Playwright
        run: yarn playwright install

      - name: Executando testes E2E
        run: yarn run e2e

      - name: Salvando relatórios de testes
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./playwright-report
          name: Relatório de Testes E2E
          
  # Job 3: Deploy Simplificado (Sem jobs fantasma e conectado ao fluxo correto)
  deploy:
    runs-on: ubuntu-latest
    needs: [unidade, e2e-tests]

    steps:
      - name: Simulação de Deploy
        run: echo 'Deploy sendo realizado...'